version: '3.7'

services:

  example:
    container_name: example
    build:
      context: .
      dockerfile: Dockerfile
    command: [ 'sh', 'run_prod.sh' ]
    restart: on-failure
    network_mode: host
    privileged: true
    volumes:
      - /var/run/dbus/:/var/run/dbus/:z
    environment:
      - EXAMPLE_PORT=${EXAMPLE_EXTERNAL_PORT}
      - METRICS_PORT=${EXAMPLE_METRICS_PORT}
    stdin_open: true
    tty: true
